# Generated by Django 5.2.10 on 2026-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dresses/'),
        ),
    ]
